MySQLDataSource = "root@tcp(localhost:3306)/test"
MQuri          = "amqp://guest:guest@localhost:5672/"
MQexchangeName = "test-exchange"
MQexchangeType = "direct"
MQroutingKey   = "test-key"
MQqueueName    = "test-queue"